### ISSUE TITLE
FixShape.to_triangulation method not found

### ISSUE THREAD

**Issue by martinstarman** [iShape-Rust/iTriangle#1]
Hi, I used the latest version of your libraries and the example in readme does not work. 

I have clean project with these Cargo.toml dependencies:
```
i_float = "0.8.0"
i_overlay = "0.23.0"
i_shape = "0.14.0"
i_triangle = "0.17.0"
```

My code:
```
use i_overlay::bool::fill_rule::FillRule;
use i_shape::fix_shape::FixShape;
use i_triangle::triangulation::triangulate::Triangulate;

fn main() {
    let shape = FixShape::new_with_contour_and_holes([].to_vec(), [[].to_vec()].to_vec());
    let triangulation = shape.to_triangulation(Some(FillRule::NonZero));
}
```

`cargo check` returns:
```
error[E0599]: no method named `to_triangulation` found for struct `FixShape` in the current scope
 --> src\main.rs:7:31
  |
7 |     let triangulation = shape.to_triangulation(Some(FillRule::NonZero));
  |                               ^^^^^^^^^^^^^^^^ method not found in `FixShape`
```

When I change Cargo.toml dependencies to:
```
i_overlay = "0.21.0"
i_shape = "0.13.0"
```
everything works. I'm using `cargo 1.76.0 (c84b36747 2024-01-18)`

**Comment by NailxSharipov** [comment]
Hi, martinstarman.

Thanks for your report.

I fixed/up iTriangle dependencies to:

i_float = "^0.8"
i_shape = "0.14.0"
i_overlay = "0.23.0"

Must be fine at 0.18.0

I have exact doc-code test at tests/doc_tests.rs and it passed successfully

**Comment by martinstarman** [comment]
It is ok now. Thanks!!
